import SparklesIcon from '@/components/SparklesIcon'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + "bg-gradient-to-b from-blue-500 to-purple-300"}>
        <main className='p-4 max-w-2xl mx-auto'>
          <header className='flex justify-between my-2 sm:my-8'>
            <Link href= "/" className="flex gap-1">
              <SparklesIcon />
              <span>Epic Captions</span>
            </Link>
            <nav className='flex items-center gap-2 sm: gap-6 text-white/80 text-sm sm:text-bas'>
              
            </nav>
          </header>
          
        </main>
        {children}
        </body>
    </html>
  )
}
